name: check

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: blog

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup problem matchers
        run: echo "::add-matcher::.github/jekyll-problem-matcher.json"

      - name: Build with Jekyll
        run: bundle exec jekyll build --lsi
        env:
          JEKYLL_ENV: production
        working-directory: blog
